apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      app: my-release
  replicas: 3
  template:
    metadata:
      labels:
        app: my-release
    spec:
      containers:
      - name: my-release
        image: bitnami/nginx:$IMAGE_TAG
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
spec:
  selector:
    app: my-release
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
